spring:
  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html; charset=utf-8
    suffix: .ftl
    template-loader-path: classpath:/template
    settings:
      number_format: 0

#日志配置
logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: ./bird.log
